---
galaxy_info:
  author: buluma
  role_name: container_docs
  description: Change package manager configuration to install docs and manpages.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.12"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - Candidate
    - name: EL
      versions:
        - "8"
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - containerdocs

dependencies: []
