# meta file
---
galaxy_info:
  author: buluma
  role_name: dnsmasq
  company: ShadowNet
  description: Set up dnsmasq in Debian-like systems.
  license: Apache-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - networking
    - dns
dependencies: []
