---
- name: apt-key add
  ansible.builtin.apt_key:
    keyring: "{{ item.keyring }}"
    url: "{{ item.url }}"
    id: "{{ item.id }}"
    state: "{{ item.state }}"
  loop: "{{ _apt_key }}"
  register: result
  until: result is succeeded

- name: apt-add-repository
  ansible.builtin.apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ _apt_repository }}"
  register: result
  until: result is succeeded

- name: apt-get install
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _apt }}"
  register: result
  until: result is succeeded
