---
galaxy_info:
  author: Michael Buluma
  namespace: buluma
  role_name: gnome
  description: Install Gnome on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - gnome

dependencies: []
