---
galaxy_info:
  author: Michael Buluma
  namespace: buluma
  role_name: setuptools
  description: Install dependecies to support the Ansible setuptools modules.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - Candidate
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - coredependencies

dependencies: []
