---
galaxy_info:
  author: Robert de Bock
  role_name: image_builder
  description: Allow your system to use Lorax, the image builder.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - imagebuilder

dependencies: []
