---
- name: Ensure apache is installed on RHEL.
  ansible.builtin.package:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit, true) }}"
