---
galaxy_info:
  author: Michael Buluma
  namespace: buluma
  role_name: vim
  description: Install vim on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: Fedora
      versions:
        - 33
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - vim
    - server
    - sudo
    - system

dependencies: []
