---
galaxy_info:
  author: Michael Buluma
  namespace: buluma
  role_name: npm
  description: Install npm on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - bullseye
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - npm
    - nodejs

dependencies: []
