---
galaxy_info:
  author: RMichael Buluma
  namespace: buluma
  role_name: powertools
  description: Enable powertools repository on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - 8

  galaxy_tags:
    - powertools

dependencies: []
