---
- name: Rpm --import
  vars:
    ansible_python_interpreter: "python3"
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    fingerprint: "{{ item.fingerprint }}"
    state: "{{ item.state }}"
  loop: "{{ _rpm_key }}"
  register: result
  until: result is succeeded

- name: Yum-config-manager --add-repo
  ansible.builtin.yum_repository:
    file: "{{ item.file }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    priority: "{{ item.priority }}"
    module_hotfixes: "{{ item.module_hotfixes }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state }}"
    reposdir: "{{ item.reposdir | default('/etc/zypp/repos.d') }}"
  loop: "{{ _yum_repository }}"

- name: Zypper install
  vars:
    ansible_python_interpreter: "python3"
  ansible.builtin.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    extra_args: "--allow-vendor-change"
  loop: "{{ _zypper }}"
  register: result
  until: result is succeeded
