---
galaxy_info:
  author: Robert de Bock
  role_name: awx
  description: Install and configure AWX on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: 2.8

  platforms:
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - awx
    - centos
    - server
    - sudo
    - system

dependencies: []
