---
roles:
  - name: buluma.bootstrap
  - name: buluma.buildtools
  - name: buluma.cron
  - name: buluma.core_dependencies
  - name: buluma.epel
  - name: buluma.httpd
  - name: buluma.mysql
  - name: buluma.openssl
  - name: buluma.php
  - name: buluma.python_pip
  - name: buluma.selinux
collections:
  - name: ansible.posix
  - name: community.mysql
  - name: ansible.posix
  - name: community.crypto
