---

- name: zypper install
  vars:
    ansible_python_interpreter: "python3"
  ansible.builtin.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _zypper }}"
  register: result
  until: result is succeeded
