---
galaxy_info:
  author: buluma
  role_name: collectd
  description: Install and configure collectd on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: EL
      versions:
        - "8"
    - name: Debian
      versions:
        - bullseye
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - collectd

dependencies: []
