---
roles:
  - name: buluma.bootstrap
  - name: buluma.buildtools
  - name: buluma.cron
  - name: buluma.epel
  - name: buluma.httpd
  - name: buluma.openssl
  - name: buluma.python_pip
  - name: buluma.selinux
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: ansible.posix
