---
galaxy_info:
  author: Michael Buluma
  namespace: buluma
  role_name: local
  description: Local Tests
  license: Apache-2.0
  company: none
  min_ansible_version: "2.10"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - server

dependencies: []
