---
galaxy_info:
  author: Robert de Bock
  role_name: zabbix
  description: Install and configure Zabbix on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - artful

  galaxy_tags:
    - zabbix
    - installer
    - package
    - centos

dependencies:
  - robertdebock.httpd
  - robertdebock.mysql
