---

galaxy_info:
  namespace: buluma
  role_name: transmission
  author: Michael Buluma
  description: Ansible Role for Transmission Installation
  company: ShadowNet
  license: Apache-2.0
  min_ansible_version: "4.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - system
dependencies: []
