---
galaxy_info:
  role_name: transmission
  author: buluma
  description: Ansible Role for Transmission Installation
  company: ShadowNet
  license: Apache-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - system
dependencies: []
