---
# Â©Copyright 2015-2016 Hewlett Packard Enterprise Development Company, LP

monasca_os_dependencies:
  - python-devel
  - python-pip
  - python-virtualenv
  - python-PyYAML
  - libxml2-devel
  - libxslt-devel
  - libffi-devel
  - openssl-devel
  - gcc
  - lshw
