---
galaxy_info:
  author: Michael Buluma
  role_name: elastic_repo
  namespace: buluma
  description: Install the Elastic repository on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: "2.12"

  platforms:
    - name: Amazon
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - elasticrepo

dependencies: []
