---
galaxy_info:
  author: Michael Buluma
  namespace: buluma
  role_name: mssql
  description: Install and configure mssql on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: Amazon
      versions:
        - Candidate
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - mssql

dependencies: []
