---
galaxy_info:
  author: buluma
  role_name: docker
  description: Install and configure Docker (non-CE) on your system.
  license: Apache-2.0
  company: ShadowNet
  min_ansible_version: "2.10"

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - "34"
        - "35"
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - docker

dependencies: []
